// Writes apps/commander-recommender's release version into a generated
// module inside src/ (rootDir: src, so it has to live there to be importable
// by spellbook.ts without reintroducing the __dirname/rootDir mismatch that
// broke a deploy once — see spellbook.ts's own comment). spellbook.ts reads
// APP_VERSION back to build its User-Agent, so the identifying header can no
// longer drift behind the release.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const serverRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const recommenderPkg = JSON.parse(readFileSync(join(serverRoot, '..', 'package.json'), 'utf8'));

const contents =
  '// Generated by scripts/write-version.mjs during the server build. Do not edit.\n' +
  `export const APP_VERSION = '${recommenderPkg.version}';\n`;

writeFileSync(join(serverRoot, 'src', 'version.generated.ts'), contents);
