// Generated by scripts/write-version.mjs during the server build (see its
// prebuild hook). Not edited by hand — the committed value below is only a
// placeholder so `tsc` passes before any build has run.
export const APP_VERSION = '0.0.0';
